export { default as Calculator } from './Calculator/Calculator'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as HomePage } from './Home/HomePage'
export { default as Maps } from './Maps/Maps'
export { default as Tables } from './Tables/Tables'
export { default as Contact } from './Contact/Contact'
export { default as Charts } from './Charts/Charts'